PRODUCT_LINE = [
    ("001", "Salidas Llegadas Palma y Formentera"),
    ("002", "Envíos Menorca e Ibiza"),
    ("003", "Salidas Llegadas Navarra"),
]

PAYMENT_TYPE = [
    ("P", "Pagados por el remitente"),
    ("D", "Debidos o pagados por el consignatario"),
]

SERVICE_TYPE = [
    ("U", "Envíos Urgentes, esto es envíos a España, Protugal, Andorra o Gibraltar."),
    ("I", "Envíos Internacionales, (resto de países de los considerados Urgente). "),
    ("F", "Envíos por avión a Canarias y Madeira"),
    ("T", "Envíos de Temperatura Controlada"),
    ("E", "Ecommerce"),
]

PRINTER_TYPE = [
    ("L", "Laser (devuelve un PDF)"),
    ("P", "Zebra (devuelve la etiqueta en lenguaje ZPL)"),
    ("Z", "Zebra (devuelve la etiqueta en lenguaje EPL)"),
    ("T", "Toshiba (devuelve la etiqueta en formato TOSHIBA)"),
    ("S", "SATO (devuelve la etiqueta en formato SBPL)"),
]


# Los estados en los que se puede encontrar un envío documentado son los siguientes:
SHIPMENT_STATE = [
    ("1", "Pendiente"),
    ("2", "Retenida"),
    ("4", "Descuadrada"),
    ("5", "Validada"),
    ("6", "Transmitida"),
]

# Las situaciones en las que se puede encontrar un envío,
# así como sus bultos, son las siguientes:
SHIPMENT_LOCATION = [
    ("CTI", "CARGA CAMION T. INTERNACIONAL"),
    ("CTN", "CARGA CAMION T.NACIONAL"),
    ("CTO", "SALIDA PLAZA ORIGEN"),
    ("CTT", "SALIDA PLAZA TRANSITO"),
    ("DEV", "DEVOLUCION ORIGEN"),
    ("DOC", "DOCUMENTACION"),
    ("EAD", "ENTRADA ADUANADAS"),
    ("EGS", "ENTRADA ZONA G.SUPERFICIE"),
    ("ENT", "ENTREGA"),
    ("ERC", "SALIDA A REPARTO"),
    ("FEC", "FECHA DE ENTREGA CONCERTADA"),
    ("SAD", "SALIDA ADUANAS"),
    ("SRP", "SALIDA A REPARTO"),
    ("TRA", "TRANSITO"),
    ("TRD", "ENTRADA PLAZA DESTINO"),
    ("TRO", "ENTRADA PLAZA ORIGEN"),
    ("TRT", "ENTRADA PLAZA TRANSITO"),
    ("ANT", "ANULADO"),
    ("BAJ", "BAJA – (Cancelado)"),
    ("DEP", "EN DESTINO PARCIAL"),
    ("DET", "EN DESTINO"),
    ("DOP", "DEVOLUCION ORIG. PARCIAL"),
    ("DOT", "DEVOLUCION ORIGEN"),
    ("ENP", "ENTREGADO PARCIAL"),
    ("ERP", "ENTREGA RECADERO PARCIAL"),
    ("ERT", "ENTREGA RECADERO"),
    ("EYD", "ENTRAGADO DEVUELTO A ORIGEN"),
    ("FET", "FECHA CONCERTADA"),
    ("INT", "INCIDENCIA"),
    ("NOT", "DOCUMENTADO"),
    ("PEN", "PENDIENTE"),
    ("REC", "RECOGIDA"),
    ("REP", "RECOGIDA PARCIAL"),
    ("SRT", "SALIDA A REPARTO"),
    ("TRP", "EN TRANSITO PARCIAL"),
    ("I01", "DIRECCIÓN INCORRECTA"),
    ("I02", "CERRADO TEMPORAL"),
    ("I03", "CERRADO HASTA NUEVA ORDEN"),
    ("I04", "DESTINATARIO AUSENTE"),
    ("I05", "DESTINATARIO NO DISPONE DE EFECTIVO"),
    ("I06", "DESTINATARIO NO ACEPTA REEMBOLSO"),
    ("I07", "DESTINATARIO NO ACEPTA PORTES DEBIDOS"),
    ("I08", "RECOGERÁN EN AGENCIA"),
    ("I09", "DEPOSITO CON ENTREGAS PARCIALES / TOTALES"),
    ("I10", "FESTIVO LOCAL"),
    ("I11", "RECOGIDA FUERA DEL HORARIO PACTADO"),
    ("I12", "DOCUMENTACIÓN DE ADUANAS NO CONFORME"),
    ("I13", "CONTENEDOR NO EMBARCADO"),
    ("I14", "PENDIENTE DE FECHA CONCERTADA"),
    ("I15", "RETRASO EN ADUANAS"),
    ("I16", "FUERZA MAYOR"),
    ("I19", "MERCANCÍA NO RECOGIDA"),
    ("I20", "RESERVA DE BULTO/S SIN EMBALAR"),
    ("I21", "RESERVA BULTO/S DAÑADO/S"),
    ("I22", "RESERVA BULTO/S ABIERTO/S"),
    ("I23", "RESERVA BULT/S SIN ETIQUETA"),
    ("I26", "RETENER POR ORDEN DEL CLIENTE"),
    ("I27", "FALTA NÚMERO DE DEVOLUCIÓN"),
    ("I28", "FALTA ALBARÁN DEL REMITENTE"),
    ("I29", "RETENER, SERVICIO DE REEMBOLSO NO AUTORIZADO"),
    ("I30", "RECHAZO, NO PEDIDO"),
    ("I31", "RECHAZO, POR INVENTARIO"),
    ("I32", "RECHAZADO, PEDIDO ANULADO"),
    ("I33", "RECHAZADO, OTRA FECHA DE ENTREGA"),
    ("I34", "RECHAZADO, OTROS MOTIVOS"),
    ("I35", "CONSIGNATARIO NO ACEPTA ENTREGAS PARCIALES"),
    ("I50", "CERRADO, REAL DECRETO COVID19"),
]

ERRO_CODE = {
    "ERROR_A01": "Error de autenticación. Credenciales no válidas. Por favor revise su usuario y contraseña.",  # noqa
    "ERROR_D01": "No puede ser null",
    "ERROR_D02": "Valor no permitido. Los valores permitidos son: [...]",
    "ERROR_D03": "Valor demasiado largo. Max: [...]",
    "ERROR_D04": "Valor ENTERO es demasiado largo. Max: [...]",
    "ERROR_D05": "Valor DECIMAL es demasiado largo. Max: [...]",
    "ERROR_D06": "El remitente informado no esxiste en nuestra BD.",
    "ERROR_D07": "La línea de producto no es válida.",
    "ERROR_D08": "El tipo de servicio no es válido para el país de destino.",
    "ERROR_D09": "Cliente no existe en nuestra BD.",
    "ERROR_D10": "El formato de la fecha es incorrecto. Formato admitido: [...]",
    "ERROR_D11": "La fecha informada no puede ser menor que la fecha de hoy.",
    "ERROR_D12": "Hora con formato incorrecto. Formato admitido: [...]",
    "ERROR_D13": "El compromiso hora informado no existe. Valores posibles: [...]",
    "ERROR_D14": "El nombre del consignatario es obligatorio.",
    "ERROR_D15": "La dirección del consignatario es obligatoria.",
    "ERROR_D16": "La población del consignatario es obligatoria.",
    "ERROR_D17": "El código postal del consignatario es obligatorio.",
    "ERROR_D18": "La provincia del consignatario es obligatoria.",
    "ERROR_D19": "El país del consignatario es obligatorio.",
    "ERROR_D20": "La dirección del consignatario no existe en nuestra BD.",
    "ERROR_D21": "El código postal del consignatario no existe en nuestra BD.",
    "ERROR_D22": "No se ha podido grabar e consignatario.",
    "ERROR_D23": "No se ha podido grabar el albarán.",
    "ERROR_D24": "No se han podido generar las etiquetas.",
    "ERROR_D25": "No se ha encontrado el albarán en nuestra BD.",
    "ERROR_D26": "Impresora no válida. Los tipos admitidos son: [...]",
    "ERROR_D27": "Debe haber al menos un bulto.",
    "ERROR_D28": "El peso debe ser informado.",
    "ERROR_D29": "El idioma elegido no es válido. Los valores posibles son: [es, uk, fr, it, de, pt]",  # noqa
    "ERROR_D30": "El Consignatario informado no existe en nuestra BD.",
    "ERROR_D31": "Error al intentar transformar el dato al tipo final",
    "ERROR_D32": "Error general parseando DTO a entidad",
}
